codecov:
  branch: master

comment:
  require_head: false
  require_base: false

coverage:
  status:
    project:
      default:
        # Don't fail the PR status on small coverage fluctuations.
        threshold: 1%
    patch:
      default:
        informational: true
